### PR TITLE
[README.md] Add information to start the test directly from python

### PR DESCRIPTION
**Pull request by olivier-stasse**
Gives proper boolean values for compiling and installing in the right directory.

### CODE REVIEW

**Comment by nim65s** [comment]
Why do you need those CMake variables ? Is `test_ws/install/lib/pythonX/dist-packages/` an issue ?

**Comment by olivier-stasse** [comment]
This is to mimic the fact that all the binaries are installed in site-packages.
Am I wrong on that ?

**Comment by nim65s** [comment]
I think that catkin will automatically add your workspace python configuration to the PYTHONPATH if you use his standard, while if you use another, you will have to manually set your environment

**Comment by olivier-stasse** [comment]
Currently I have one script doing this for openrobots. I was making sense for me to use the same script. But I agree that it makes also sense to use the setup.bash file from ros...

**Comment by nim65s** [comment]
This README explicitely ask to source setup.bash

**Comment by olivier-stasse** [comment]
Thanks, this is fixed.

**Review by nim65s — APPROVED** [review]

**Pull request merged**
