### PR TITLE
[Python] fix paths for applis

### PR DESCRIPTION
**Pull request by nim65s**
I don't even understand what this `/lib/` is supposed to mean.
Here is the issue I had:
```
Traceback (most recent call last):
  File "/ws/src/talos_integration_tests/scripts/test_kine.py", line 67, in <module>
    runTest()
  File "/ws/src/talos_integration_tests/scripts/test_kine.py", line 51, in runTest
    "r").read().split("\n")
IOError: [Errno 2] No such file or directory: '/ws/src/talos_integration_tests/../../lib/talos_integration_tests/appli.py'
```

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Thanks for the fix.
My only explanation for this policy is to have two executables with the same name but do the difference with the package name.

**Comment by olivier-stasse** [comment]
@nim65s Well the main point is probably is that appli.py and test_kine.py are python scripts handled by two different python interpreters: test_kine.py is a classically used execution script where appli.py is supposed to be send to the python interpreter embedded in the SoT. I am not satisfied by how it is handled right now. For convenience it is located at the same position that test_kine.py but it is a python file to be remotely interpreted and not to be locally interpreted. Still I would like to keep it different from modules which are installed on the robot or in the SoT interpreter scope. It shows that it is possible to "send" control python commands to the control infrastructure. This is connected with this PR because maybe we should find a proper way to store such kind of files.

**Comment by nim65s** [comment]
I see. If I understtand correctly your need, you want a path to the current installed version of this package on a potentially remote system. Right ?

If so, I can suggest to install this script with the package, and let python's import system find it.

Eg. :
```python
# source: talos_integration_tests/talos_integration_tests/appli.py 
# installed in ${PYTHON_SITELIB}/talos_integration_tests/appli.py
from dynamic_graph.sot.core.meta_tasks_kine import MetaTaskKine6d, MetaTaskKineCom, gotoNd
from dynamic_graph.sot.core.matrix_util import matrixToTuple
from numpy import eye

def init_application():
    taskRH = MetaTaskKine6d('rh',robot.dynamic,'rh',robot.OperationalPointsMap['right-wrist'])
    handMgrip = eye(4)
    handMgrip[0:3,3] = (0.1,0,0)
    taskRH.opmodif = matrixToTuple(handMgrip)
    ...
```

And
```python
# source talos_integration_tests/scripts/test_kine.py
...
rospy.loginfo('initialize SoT')
runCommandClient('from talos_integration_tests.appli import init_application')
runCommandClient('init_application()')
rospy.loginfo('Stack of Tasks launched')
```

Would it suits your need ?

**Comment by nim65s** [comment]
But right now, you are not running a remote appli.py, are you ? If I understand correctly, the `launchScript` function open locally the file, parse it (this is **bad**), and send it line by line to the remote interpreter, right ?

**Pull request merged**
